### ISSUE TITLE
Plugins interface not shown in preferences

### ISSUE THREAD

**Issue by SoftExpert** [ArchGPT/insomnium#1]
### Expected Behavior

Plugins tab should appear in Preferences

### Actual Behavior

Plugins tab does not appear in Preferences

### Reproduction Steps

1. Click on Preferences button
2. Notice there is no Plugins tab

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It's understandable that the whole plugins ecosystem from Insomnia cannot be integrated as such, but an alternative should be found - some plugins have a real added value.

### Insomnium Version

v0.1

### What operating system are you using?

Other Linux

### Operating System Version

Manjaro 23.0.3

### Installation method

locally built from source

**Comment by archywillhe** [comment]
Thanks for letting me know that plugin is important. I just [re-enabled it in v0.1.1](https://github.com/ArchGPT/insomnium/releases/tag/v0.1.1). 

Previously I thought there was a problem, but looks like it's working fine in production now. But do let me know if you run into anything werid!

**Comment by archywillhe** [comment]
marking this as close now; feel free to submit any new tickets!
