### ISSUE TITLE
Website - Potential Security Issue (Firefox

### ISSUE THREAD

**Issue by felix-staud** [ArchGPT/insomnium#101]
### Expected Behavior

I am securely able to visit the website https://archgpt.dev/insomnium

### Actual Behavior

Firefox blocks the connection to https://archgpt.dev/insomnium

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Additional Information

![image](https://github.com/ArchGPT/insomnium/assets/50131232/c64a610a-f29e-4ff4-8105-34e7fd20e19a)

### Operating System Version

Windows - Firefox 119.0.1 (64-bit)

**Comment by archywillhe** [comment]
I'm unable to replicate this; maybe you can follow this tutorial to [upgrade your firefox, etc](https://campus.barracuda.com/product/ContentShield/doc/73699516/how-to-clear-the-hsts-cache-or-disable-hsts-for-firefox/)
