### ISSUE TITLE
Missing support for plugin-defined workspace actions

### ISSUE THREAD

**Issue by techchrism** [ArchGPT/insomnium#109]
### Expected Behavior

Items exported from a plugin's `module.exports.workspaceActions` get populated in the workspace dropdown

### Actual Behavior

The workspace dropdown contains no plugin content

### Reproduction Steps

Can be replicated with any plugin that defines workspace actions. One such example is https://insomnia.rest/plugins/insomnia-plugin-repo-sync-3

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Additional Information

It appears the react state getter for `actionPlugins` in `packages/insomnia/src/ui/components/dropdowns/workspace-dropdown.tsx` is missing: <https://github.com/ArchGPT/insomnium/blob/8e562eb3f8a64fc5c2ab1a78caf198b699d371b7/packages/insomnia/src/ui/components/dropdowns/workspace-dropdown.tsx#L49C64-L49C64>

This regression was introduced in the massive commit seen here: <https://github.com/ArchGPT/insomnium/commit/0496695466e49cea118c4d7d0f96d9021c1f1450#diff-c205c4e3fa2d0d5ea9b8feabe3210440ab35db3c06901dd72ba77d891cdaa911>

I guess this might fall under the "etc" in "removed sentry, segment, etc, and updated readme"? If this was intentional, it's not clear to me what the reasoning was.

### Insomnium Version

0.2.3-a

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

installer

**Comment by TCB13** [comment]
This might be related: https://github.com/francbohuslav/insomnia-plugin-uu-sync/issues/4
