### ISSUE TITLE
Couldn't open the app in MacOS

### ISSUE THREAD

**Issue by jewei** [ArchGPT/insomnium#21]
### Expected Behavior

Should be able to launch the app without errors.

### Actual Behavior

![Screenshot 2023-10-05 at 2 01 56 PM](https://github.com/ArchGPT/insomnium/assets/51693/bc56fc67-4bf7-46e5-a22f-84933416c23c)

### Reproduction Steps

1. Download Insomnium.Core-0.1.3.dmg from https://github.com/ArchGPT/insomnium/releases/tag/core%400.1.3
2. Drag and drop the app into Application folder.
3. Double click on the app from Application folder (Finder).

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

Insomnium 0.1.3b

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma

### Installation method

Download from https://github.com/ArchGPT/insomnium/releases

**Comment by Vanderhoof** [comment]
Try this:
- in Applications right-click on Insomnium icon
- hold opt (or cmd) button on keyboard and click Open

**Comment by jakobmulvad** [comment]
I have the same issue. I tried holding cmd + open and it didn't change anything. I also tried "System settings -> Privacy & Security -> Open anyway":
![image](https://github.com/ArchGPT/insomnium/assets/5014261/37fb391d-c94b-4490-a386-504464f4d24e)
...but i get same error. Maybe my employer are applying extra strict security policies that doesn't allow me to bypass this. Dunno 🤷‍♂️

**Comment by k3mist** [comment]
im not a mac user but just wanted to say thank you for the fork and removing all the BS @archywillhe !

ill be installing this on linux in the very near future. just too busy right now 

thank you again!

**Comment by jewei** [comment]
Thanks. @Vanderhoof method (cmd + open) works for me.

**Comment by K-J-HYEON** [comment]
I Got It! Thanks for posting :)

**Comment by elovin** [comment]
@archywillhe very nice thank you :)

**Comment by riezahughes** [comment]
You can actually open it without issues. If you put it into the applications folder, then right click/open it'll come up a different dialogue that'll allow you to use it.

**Comment by MB175** [comment]
> I have the same issue. I tried holding cmd + open and it didn't change anything. I also tried "System settings -> Privacy & Security -> Open anyway": ![image](https://user-images.githubusercontent.com/5014261/272807912-37fb391d-c94b-4490-a386-504464f4d24e.png) ...but i get same error. Maybe my employer are applying extra strict security policies that doesn't allow me to bypass this. Dunno 🤷‍♂️

Same, managed Macs do this sometimes

**Comment by hamburml** [comment]
Same issue here :/

**Comment by root0x** [comment]
Open system preferences -> Priacy & Security -> scroll down to security -> see where it says insomnum and click open anyway

**Comment by MB175** [comment]
> Open system preferences -> Priacy & Security -> scroll down to security -> see where it says insomnum and click open anyway

This will unfortunately no work, since many companies role out profiles to block trusting  uncommon signing keys

**Comment by root0x** [comment]
> This will unfortunately no work, since many companies role out profiles to block trusting uncommon signing keys

Thats true but it will help out people trying to install it on their personal machines

**Comment by katespencer-bayer** [comment]
For those who are stuck but have the ability to sudo, try this:

```
sudo xattr -r -d com.apple.quarantine /Applications/Insomnium.app
```

Then try running it. I've had to do this a few times before on my MDM managed device. Not sure why sometimes "open anyway" works, sometimes right-click -> open works, and sometimes an app has to be removed from quarantine, on the same device w/ the same MDM profile, but there it is.

**Comment by nsrosenqvist** [comment]
> Aw I see. Thanks for posting! I'm still waiting for my apple developer enrollment and then I can have the app undergoes Apple notarization and there won't need to this a hack around anymore

Is there anything to report on your enrollment? :)

**Comment by archywillhe** [comment]
@nsrosenqvist  Oh I got it; the MacOS build should be working without problem now; 

I've just rebuilt [Insomnium 0.2.3-a ](https://github.com/ArchGPT/insomnium/releases/tag/core%400.2.3-a)

@nsrosenqvist  You can [click here to download]() the signed build

Thanks! (I'm closing this for now; feel free to reopen if anything weird happens)

------- 

(Been busy with a Custom GPT integration; new build coming soon!)

**Comment by archywillhe** [comment]
(oops sorry I accidentally uploaded a build with half-implemented features; reverting it now & and re-uploaded a properly notarized build )
