### ISSUE TITLE
Windows: package name matches Insomnia

### ISSUE THREAD

**Issue by paulius-valiunas** [ArchGPT/insomnium#37]
### Expected Behavior

Insomnium should be either updated as a separate app or not touched at all by winget

### Actual Behavior

Insomnium is "updated" to Insomnia 8.2.0 by winget

### Reproduction Steps

1. install Insomnium
2. run `winget upgrade`
3. winget shows Insomium with the id `insomnia.insomnia` and "latest available" version 8.2.0
4. run `winget upgrade --all`
5. winget replaces Insomnium with Insomnia

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Additional Information

Insomnium should have its own package name, but right now the package name matches that of Insomnia: `insomnium.insomnium`. I think this name is derived from the package name in `./packages/insomnia/package.json`. More info on how the package name is determined can be found here: https://github.com/microsoft/winget-cli/discussions/3033

### Insomnium Version

0.2.1-b

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### Installation method

GitHub releases

**Comment by archywillhe** [comment]
>I think this name is derived from the package name in ./packages/insomnia/package.json. More info on how the package name is determined can be found here: https://github.com/microsoft/winget-cli/discussions/3033

thanks! good find! I will patch this asap in the next release; looks like a windows-only bug (I've already changed the name in package.json at root; if the fix is about changing pacakges/insomnia, then I need to test it out thoroughly as it may break other stuff)

**Comment by ShayBox** [comment]
Could this also be added to winget?
