### ISSUE TITLE
No icon on linux in taskbar

### ISSUE THREAD

**Issue by lazystone** [ArchGPT/insomnium#38]
### Expected Behavior

Some icon would be nice to have.

### Actual Behavior

<img width="66" alt="image" src="https://github.com/ArchGPT/insomnium/assets/2885029/2110582c-69f4-498e-b0f8-09198b935c42">

### Reproduction Steps

1. Install 0.2.1-b

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

0.2.1-b

### What operating system are you using?

Ubuntu

### Operating System Version

KDE Neon 5.2.7

### Installation method

deb

### Last Known Working Insomnium version

0.1.3

**Comment by lazystone** [comment]
Actually, now I think that application icons didn't work correctly even in 0.1.3

In 0.1.3 I see default InsomniA icon, which I guess packed in Electron, but icon in the deb package is different.

**Comment by lazystone** [comment]
Ok, I think it's related to https://github.com/electron-userland/electron-builder/issues/5294

Inside the deb package icon is indeed in the 0x0 folder.

So I guess solution would be to provide pre-scaled icons, according to https://www.electron.build/icons.html#linux

**Comment by lazystone** [comment]
@archywillhe it's almost fixed, one more line is needed: `icon: 'src/icons'`

In `electron-builder.config.js`:

```json
  linux: {
    artifactName: `${BINARY_PREFIX}-\${version}.\${ext}`,
    executableName: 'insomnia',
    icon: 'src/icons',
```

Tried it locally - can see icon in the taskbar now.

**Comment by archywillhe** [comment]
thanks! meriging your pr now :)
