### ISSUE TITLE
Undo in Address bar

### ISSUE THREAD

**Issue by jb-alvarado** [ArchGPT/insomnium#43]
### Expected Behavior

When changing something in the request address, clicking send and after clicking back in the address bar -> Undo (Strg+Z) should undo the last change.

### Actual Behavior

Clicking undo does not update changing in address bar.

### Reproduction Steps

1. Create Request
2. make change in address bar
3. click send
4. click in address bar
5. hit undo

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

0.2.1-b

### What operating system are you using?

Other Linux

### Operating System Version

fedora 38

### Installation method

dnf

**Comment by archywillhe** [comment]
aw good point; I think this is an Insomnia's default behaviour as clicking on send somehow also cleared some UI cache

I'll resolve this in the next release
