### ISSUE TITLE
Bad name of application on deb package

### ISSUE THREAD

**Issue by rsantellan** [ArchGPT/insomnium#46]
### Expected Behavior

I should be able to install insomnia and insomnium side by side, just to check if everything is imported correctly.

### Actual Behavior

![image](https://github.com/ArchGPT/insomnium/assets/1820598/79953851-2fec-42f8-9c19-dc85320801f5)

Only can install one.

### Reproduction Steps

1. Download deb package
2. Try to installed.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

0.2.1-b

### What operating system are you using?

Ubuntu

### Operating System Version

20.04.1-Ubuntu

### Installation method

deb

**Comment by archywillhe** [comment]
oh now; aww thanks for spotting this; looks like deb uses a diff place for identifier than other os; the fix will be out in the next release

**Comment by imithu** [comment]
Sorry to say it's not solved yet.
I tried to install Insomnium 0.2.2


```sh
(Reading database ... xxxxx files and directories currently installed.)
Preparing to unpack Insomnium.Core-0.2.2.deb ...
Unpacking insomnium (0.2.2) ...
dpkg: error processing archive Insomnium.Core-0.2.2.deb (--install):
trying to overwrite '/usr/share/applications/insomnia.desktop', which is also in package insomnia 2023.5.8
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.70+nmu1) ...
Errors were encountered while processing:
Insomnium.Core-0.2.2.deb
```

**Comment by archywillhe** [comment]
ooh i see..

I think lazystone just found a fix and did a PR
so this should be resolved in the next build
