### ISSUE TITLE
Taskbar icon is of low resolution when using large taskbar icons on KDE Plasma

### ISSUE THREAD

**Issue by Absolutely-Free** [ArchGPT/insomnium#47]
### Expected Behavior

I have a huge monitor and crappy vision, so I use a large vertical taskbar (72px width) in KDE Plasma with large icons. The taskbar icons usually are scaled from a higher resolution source.

### Actual Behavior

The icon for insomnium that is being recognized by KDE seems to be one of a low resolution, so it looks pixelated when blown up to the size that I use. Compare to the others adjacent to it:

![Screenshot_20231012_042451](https://github.com/ArchGPT/insomnium/assets/93813924/1f92e4be-2801-462c-a768-73a49cf138e0)

### Reproduction Steps

1. Install Insomnium from the AUR on Arch Linux while using KDE Plasma.
2. Right click on your taskbar and increase the width to a large number (I am using 72px width).
3. Open Insomnium and view the taskbar icon.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Additional Information

This might be related to issue #38, but I am using the AUR source. I can add my scenario to that issue if you prefer.

Overall this is a very minor issue that doesn't bother me much. Thank you for the work that you are doing on this wonderful and privacy-respecting alternative!

### Insomnium Version

0.2.1_b-1

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux with KDE Plasma and kernel 6.1.57-1-lts

### Installation method

AUR

**Comment by archywillhe** [comment]
aw that's the old Insomnia icon; I will get this fixed in the next release. Thanks for posting!

**Comment by Absolutely-Free** [comment]
This was actually an issue with the version I had installed. I searched the AUR and installed the package "insomnium", but I didn't realize until later that the correct package on the AUR was "insomnium-bin".

I uninstalled "insomnium", deleted my icon-cache file, installed insomnium-bin, reinstalled kiconthemes, and rebooted. Now the icon is correct.

**Comment by archywillhe** [comment]
hmm that's quite werid; could be the difference between .gz and .deb

**Comment by Absolutely-Free** [comment]
Seems like a difference between [your pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=insomnium-bin) and [theirs](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=insomnium). Theirs is installing [this icon](https://github.com/ArchGPT/insomnium/blob/main/packages/insomnia/src/static/insomnia-core-logo_16x.png) locally, which is still the original insomnia icon and low resolution too. Yours is using [this icon](https://github.com/ArchGPT/insomnium/blob/main/packages/insomnia/src/icons/icon.png), which is the new insomnium icon you were intending.

**Comment by archywillhe** [comment]
ohh i see; thanks for the pointer
