### ISSUE TITLE
Restarting the app removes saved gRPC request bodies and breaks proto file link

### ISSUE THREAD

**Issue by Perryvw** [ArchGPT/insomnium#52]
### Expected Behavior

After restarting the app I expect the gRPC requests I created before the restart to still be valid and working. 

Specifically:

- The request gRPC Method should be the same
- The request's request body should be the same
- The link to the proto file related to the request should still be valid

### Actual Behavior

Requests have their gRPC Method reset to unselected. The request body is no longer visible because there is no gRPC method selected. It is not possible to re-select the method because it does not know what proto file the request relates to.

Selecting the same proto file does not work, presumably because the app thinks the file is the same as it was before. It does still highlight the correct file.

Only after selecting a different proto file, then selecting the desired file again, the method dropdown becomes active again. Selecting the same method as before then causes the request body to reappear as it was before, so the data _is_ in the save file somewhere.

### Reproduction Steps

- Create 2 gRPC requests using the same method in the same proto file
- Set the method in both requests to the same gRPC method from the proto
- Fill in some (different) request body for both requests
- Close the application
- Reopen the application

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Additional Information

This is quite annoying and a blocker for using Insomnium for us. 

It seems like the information is somehow there in the save file because the request body does reappear after selecting a method.
Also the correct proto file is still highlighted so presumably the proto link is also still there.

My guess would be this has something to do with the proto parsing and resolution of its imports (which are in a parent folder and require a specific proto base directory). This import resolution does seem to work while working in the same session, so not entirely sure this is the actual issue.

### Insomnium Version

0.2.1-b

### What operating system are you using?

Windows

### Operating System Version

Win10

### Installation method

downloaded exe from github releases

**Comment by archywillhe** [comment]
hey thanks for the reporting! I'll sort this out soon for the next release; (I'm not 100% sure if this is a relic from insomnia 2023.05.8 & I'll check the kong's branch to see if it is patched)
