### ISSUE TITLE
Opening the changelog causes JavaScript error

### ISSUE THREAD

**Issue by Absolutely-Free** [ArchGPT/insomnium#56]
### Expected Behavior

When opening the changelog from the menu bar, I would expect to see the changelog for insomnium (https://github.com/ArchGPT/insomnium/releases)

### Actual Behavior

A javascript error is thrown:

![Screenshot_20231013_201345](https://github.com/ArchGPT/insomnium/assets/93813924/8a69da0f-a1ee-4d28-b272-17bd6299ce84)

### Reproduction Steps

1. From the menu bar, click "Application" > "Changelog"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

0.2.0

### What operating system are you using?

Other (specify below)

### Operating System Version

Operating System: Arch Linux,  KDE Plasma Version: 5.27.8, KDE Frameworks Version: 5.110.0, Qt Version: 5.15.11, Kernel Version: 6.1.57-1-lts (64-bit), Graphics Platform: X11

### Installation method

AUR

**Comment by archywillhe** [comment]
aw good find; this is fixed in the next release

**Comment by danielvijge** [comment]
Opening the changelog from the menu now leads to https://github.com/ArchGPT/insomnium/releases/tag/core, which gives a 404 error. The correct URL would be https://github.com/ArchGPT/insomnium/releases/tag/core%400.2.2

**Comment by archywillhe** [comment]
oh yeah thanks for spotting this out; I was deciding whether to show user the versioned one, or the full changelog of all versions. I think later would would be better (so ppl can see the latest release as well as old ones, in case they are in an older ver) but I put the wrong url with `/tag/core`
