### ISSUE TITLE
[macOS] CFBundleIdentifier is still "com.insomnia.app"

### ISSUE THREAD

**Issue by core-code** [ArchGPT/insomnium#61]
### Expected Behavior

as this is not upstream insomnia the CFBundleIdentifier should not be the same as the identifier of the original project 

### Actual Behavior

the identifier is the same as upstream, making it indistinguishable to the operating system and 3rd party apps.

```
    <key>CFBundleIdentifier</key>
    <string>com.insomnia.app</string>

```

how about ```org.archgpt.insomnia```?

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Additional Information

the CFBundleIdentifier is in the ```Contents/Info.plist```file

### Insomnium Version

any

### What operating system are you using?

macOS

### Operating System Version

macOS

### Installation method

any

**Comment by archywillhe** [comment]
oh yeah I've been sorting this out; a fix is in the upcoming release today.

**Comment by core-code** [comment]
awesome, thanks!
