### ISSUE TITLE
Git overview not showing, can't commit or switch branches

### ISSUE THREAD

**Issue by maxiangelo** [ArchGPT/insomnium#68]
### Expected Behavior

Git overview is shown on the right side when opening a collection, like it did in Insomnia.

### Actual Behavior

Git overview is not there.

![image](https://github.com/ArchGPT/insomnium/assets/35735678/20c4ec7f-48e9-4db4-b34e-f4c2198e37d1)

### Reproduction Steps

Open a collection.
Overview is not there.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

0.2.1-b

### What operating system are you using?

macOS

### Operating System Version

14.0 (23A344)

### Installation method

downloaded from insomnium github page

### Last Known Working Insomnium version

no

**Comment by archywillhe** [comment]
good catch; thanks; this will be back in the next release

**Comment by maxiangelo** [comment]
Hi @archywillhe I tested the [new release](https://github.com/ArchGPT/insomnium/releases/tag/core%400.2.2) and I still cant find the git overview. I reimported the git projects, but even then the overview did not show up. Am I doing something wrong? 
![image](https://github.com/ArchGPT/insomnium/assets/35735678/606a59cd-9eb4-4ad4-a68d-2c371f2e6a2f)

![image](https://github.com/ArchGPT/insomnium/assets/35735678/81b15fa0-de70-4f66-9efd-ff454bc80dff)

**Comment by archywillhe** [comment]
oh hey; sorry this should be re-opened; I

**Comment by archywillhe** [comment]
oh hey; sorry this should be re-opened; I'm still sorting out some git stuff; I will ping here again when it's done

**Comment by archywillhe** [comment]
This is the UI you're referring to right? Will be back in the new version v0.2.3

<img width="249" alt="Screenshot 2023-10-26 at 10 12 07 PM" src="https://github.com/ArchGPT/insomnium/assets/10269911/04c38425-d74f-43f1-8e95-9257c4111fef">

**Comment by maxiangelo** [comment]
> This is the UI you're referring to right? Will be back in the new version v0.2.3
> 
> <img alt="Screenshot 2023-10-26 at 10 12 07 PM" width="249" src="https://user-images.githubusercontent.com/10269911/278464308-04c38425-d74f-43f1-8e95-9257c4111fef.png">

yes, exactly :D

**Comment by archywillhe** [comment]
yeah it's at 0.2.3 now
