### ISSUE TITLE
Insomnium making requests to updates.insomnia.rest 

### ISSUE THREAD

**Issue by tofran** [ArchGPT/insomnium#73]
### Expected Behavior

Insomnium should not be tapping back home.
Should work offline and only make requests to where the user point it to, and when the user instructs it to.

### Actual Behavior

With a firewall installed, in this case LuLu, I can see that insomnium is making requests to the following url:

```
https://updates.insomnia.rest/builds/check/mac?v=0.2.1-b&app=com.insomnium.app&channel=stable
```

<img width="1371" alt="Screenshot 2023-10-23 at 17 53 26" src="https://github.com/ArchGPT/insomnium/assets/5692603/8dabce10-472a-4d7f-9554-4ca50ce94524">

I have never accepted any privacy policy, terms of use or checkbox saying automatic updates.
Furthermore nor the License that is a plain MIT License or the readme mention that this application does tracking.

### Reproduction Steps

- Install the firewall of your choice, in this case LuLu
- Clean install Insomnium 0.2.1-b on mac `14.0 (23A344)`
- Copy .DB files from Insomnia to Insomnium
- Open Insomnium
- Insomnium will make this request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

0.2.1-b

### What operating system are you using?

macOS

### Operating System Version

14.0 (23A344)

### Installation method

Manual with Insomnium.Core-0.2.1-b.dmg frm GitHub releases

### Last Known Working Insomnium version

Haven't tried other versions

**Comment by archywillhe** [comment]
thanks for the report! hmm interesting; that shouldn't be happening as I've already disabled the version-auto-update check on start-up; probably a fn from somewhere else making that call; I'll get this fixed in the next release

**Comment by archywillhe** [comment]
aw I see; because the `setting.updateAutomatically` is stored in the db and I completely remove the fn instead of using `updateAutomatically: false`

**Comment by archywillhe** [comment]
aw I see; because the `setting.updateAutomatically` is stored in the DB (so the old config basically got copied over from Insomnia and triggered an update). So basically I need to completely remove the fn instead of using `updateAutomatically: false`

**Comment by tofran** [comment]
@archywillhe thank you very much for the quick fix and all the effort in maintaining this project!
