### ISSUE TITLE
Opening Changelog leads to 404 page

### ISSUE THREAD

**Issue by Absolutely-Free** [ArchGPT/insomnium#76]
### Expected Behavior

Changelog link should open to the Insomnium github release page.

### Actual Behavior

Opening the changelog navigates to a 404 error: https://github.com/ArchGPT/insomnium/releases/tag/core

### Reproduction Steps

Open the changelog in the menu bar in Insomnium 0.2.2

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Additional Information

It seems like you are trying to link to a release page specifically for releases that have the "core" tag, but github is expecting there to be a version number included along with that core tag. I am not sure if you can link to a general release tag like that, but I tried doing some research and couldn't find any conclusive evidence saying it is possible.

I did find [this page](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases) though, which says you can use the URL "https://github.com/ArchGPT/insomnium/releases/latest" to always link to the latest release.

### Insomnium Version

0.2.2

### What operating system are you using?

Other Linux

### Operating System Version

Operating System: Arch Linux, KDE Plasma Version: 5.27.9, KDE Frameworks Version: 5.111.0, Qt Version: 5.15.11, Kernel Version: 6.1.59-1-lts (64-bit), Graphics Platform: X11

### Installation method

AUR

**Comment by archywillhe** [comment]
oh good find... (I thought `tag/core/` would be the right place.) Thanks! fixing this in the new commit now

**Comment by archywillhe** [comment]
oh good find... (I thought `tag/core/` would be the right place.) Thanks! fixing this in the new commit now. I think 
`https://github.com/ArchGPT/insomnium/releases` will do so people can see the latest (as well as older ones (in case they were coming from an older version))
