### ISSUE TITLE
Security issue mailbox security@archgpt.net doesn't accept mail

### ISSUE THREAD

**Issue by Ilnore** [ArchGPT/insomnium#8]
### Expected Behavior

The email address referred to  in the [Security Policy](https://github.com/ArchGPT/insomnium/security/policy), [security@archgpt.net](mailto:security@archgpt.net) does not accept email.

### Actual Behavior

The email server responds with:

```
Remote server returned '554 5.0.0 < #5.0.0>'
```

Which would mean that the mailbox `security` doesn't exist?

### Reproduction Steps

1. Send mail to [security@archgpt.net](mailto:security@archgpt.net).
2. Wait for bounce reply.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

Irrelevant

### What operating system are you using?

Other (specify below)

### Operating System Version

Irrelevant

### Installation method

Irrelevant

### Last Known Working Insomnium version

Irrelevant

**Comment by archywillhe** [comment]
oh hi that was fast! I only added the address yesterday to revamp everything and I haven't set up the domain and mailbox yet.

I have read the other issue you posted, where you mentioned the same problem. Please restrain from posting twice, thanks. The mailbox will be configured in a few hours.

**Comment by archywillhe** [comment]
next time for any issue you can also reach out to me at a@0a.io
