### ISSUE TITLE
deb package installation failed

### ISSUE THREAD

**Issue by Webklex** [ArchGPT/insomnium#86]
### Expected Behavior

Update from `0.2.1-b` to `0.2.3-a` without an error

### Actual Behavior

Update failed:
```bash
Preparing to unpack Insomnium.Core-0.2.3-a.deb ...
Unpacking insomnium (0.2.3-a) ...
dpkg: error processing archive Insomnium.Core-0.2.3-a.deb (--install):
 trying to overwrite '/opt/Insomnium/libGLESv2.so', which is also in package insomnia 0.2.1-b
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Errors were encountered while processing:
 Insomnium.Core-0.2.3-a.deb
```

### Reproduction Steps

1. Install an older version like `0.2.1-b`
2. Download the latest release
3. Update to `0.2.3-a` using `dpkg`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Additional Information

Command used:
```bash
sudo dpkg -i Insomnium.Core-0.2.3-a.deb
```

### Insomnium Version

0.2.3-a

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.3 LTS

### Installation method

downloaded from the release section and installed via dpkg

**Comment by archywillhe** [comment]
hmm this could be due to a naming-update at 0.2.2; have you tried uninstalling and doing a clean install? The update should work from here on

**Comment by stitcharg** [comment]
I had the same issue, and I can confirm that removing the 0.2.1-b with `dkgp -r insomnia`, and retrying the install of the 0.2.3-a, works as expected.

**Comment by Webklex** [comment]
I can confirm that running:
```bash
sudo dpkg -r insomnia
sudo dpkg -i Insomnium.Core-0.2.3-a.deb
```
worked. Thanks for the help and an awesome project :)
